project:
  type: website

website:
  title: ""
  
  navbar:
    background: "#030D23"
    foreground: "#ffff"
    right:
      - href: ./index.qmd
        text: Home
      - href: db/db.qmd
        text: Dashboards
      - href: chart/charts.qmd
        text: Charts
      - href: blog/index.qmd
        text: Stories
      - href: about.qmd
        text: Contact
  page-footer: 
    background: "#030D23"
    left: "Copyright 2024" 
    right: 
      - icon: linkedin
        href: https://linkedin.com/company/vistales
      - icon: twitter 
        href: https://twitter.com/vistales_ 
      - icon: instagram
        href: https://instagram.com/vistales_     
  
format:
  html:
    #theme: mint
    css: styles.css
    toc: false